# Generated by Django 4.1.3 on 2022-11-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comensales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField(max_length=2)),
                ('direccion', models.CharField(default='sin direccion', max_length=20)),
            ],
        ),
    ]
