# Generated by Django 4.1.3 on 2022-12-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesero',
            name='pais',
            field=models.CharField(default='sin pais', max_length=10),
        ),
    ]
